WsServer: allow binding to existing HTTP server
adzialocha/osc-js pull request #49
Opened 2021-04-03 12:12 UTC by elgiano

Addressing issue #43 
This PR makes it possible to pass an existing server when initializing BridgePlugin, so that Express and OSC can work together on the same server.
I made the changes also to WebSocketServer Plugin, but that is not tested (I've only used Bridge so far).

Usage example:
```
  // Create a web server to serve files and listen to WebSocket connections
  const app = express();
  app.use(express.static('www'));
  const server = http.createServer(app);

  const osc = new OSC({ plugin: new OSC.BridgePlugin({
    udpServer: { port: 57100 },
    udpClient: { port: 57120 },
    wsServer: {  server }, // here we pass our HTTP server to OSC
  })});
  osc.open();

  // start http server
  server.listen(process.env.port || 8081);
```

2021-04-12 14:36 UTC, adzialocha requested changes
Super, thanks so much for this great addition @elgiano!

I have two minor nitpicks :sweat_smile: 

* Would you mind adding the new `server` option to the docstrings as well, so it will show up in the documentation?
* Can you add brackets for the if-statments instead of using the "bracket-less" style? The latter might open a door to introduce new bugs by accidentally adding / moving / removing lines

2021-04-25 10:56 UTC, elgiano commented
Done, please have an eye on it, it's my first time with esdoc, and feel free to rephrase or change anything as you see it fits :)

2021-12-02 12:55 UTC, adzialocha commented
Finally I had time to look at this again! I'm really sorry for the delay, been busy with other projects .. :crying_cat_face: But thank you so much for this contribution @elgiano !

2021-12-02 12:55 UTC, adzialocha approved these changes

2021-12-02 12:55 UTC, merged

2021-12-04 01:07 UTC, elgiano commented
Thank you!!